import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import StoreProvider from "./StoreProvider";
import { Flowbite } from "flowbite-react";
import AppFooter from "@/components/AppFooter";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//       <Header />
//       {children}</body>
//     </html>
//   );
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html>
        <head>
        
        </head>
        <body className="dark:bg-slate-900 bg-gray-200">
          {" "}
          <Flowbite>
            <Header />
            {children}

            {/* <DarkThemeToggle /> */}

            {/* <Toaster /> */}
            {/* <div className="min-h-screen"> */}
              <AppFooter />
            {/* </div> */}
          </Flowbite>
        </body>
      </html>
    </StoreProvider>
  );
}
